version: 1.0.{build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2017 Preview
install:
  - choco install gitversion.portable -pre -y
before_build:
  - gitversion /l console /output buildserver
  - build\install-blazor.cmd
build:
  verbosity: normal