version: 1.0.{build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2017 Preview
install:
  - choco install gitversion.portable -pre -y
before_build:
  - gitversion /l console /output buildserver
  - "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe" /q /a build\Microsoft.VisualStudio.BlazorExtension.vsix
build:
  verbosity: normal